### ISSUE TITLE
Implement shoutrrr to support different types of notification options

### ISSUE THREAD

**Issue by onedr0p** [topfreegames/fluxcloud#6]
https://github.com/containrrr/shoutrrr currently supports:

- gotify
- hangouts
- ifttt
- logger
- mattermost
- pushbullet
- pushover
- slack
- smtp
- standard
- teams
- telegram

This could offload a lot code to this dependency

**Comment by fdpeiter** [comment]
Hey there, @onedr0p, are you thinking of replacing the whole structure for this or just implementing an exporter? We don't want to diverge a lot from the original project, as we plan to merge it in the future.

**Comment by onedr0p** [comment]
It would be nice to support more providers, I'm looking for pushover personally. But using their package it seems like you could support much more.

**Comment by fdpeiter** [comment]
Do you want to try to add support to pushover using this lib? Would it be too hard to do that?

**Comment by onedr0p** [comment]
Not sure when/if I'll have time, I thought you guys were taking over the development, if not, you may want to make you intentions clear on the issue you posted: https://github.com/justinbarrick/fluxcloud/issues/68

**Comment by fdpeiter** [comment]
No problem! So about shoutrrr, we don't plan to drift a lot from the original project for a while. We aren't sure if the project will be reactivated or not, so we want to be able to merge on it if it does. WDYT of opening a feature request for the pushover?

**Comment by onedr0p** [comment]
Sure, but I thought that adding shoutrrr would stop people from asking for x, y or z provider

**Comment by fdpeiter** [comment]
I also believe it's something we definitely gonna take a look in the future. One of flux developers reached us and ask us to wait until they try to contact the original project developer, this is why we prefer to maintain the original structure until we wait.

**Comment by blmhemu** [comment]
Not sure but it seems like the team over at FluxCD is also implementing some kind of notification framework although it's in alpha at the moment: 
https://github.com/fluxcd/notification-controller
Do the goals of fluxcloud and fluxcd/notification-controller overlap ?

**Comment by fdpeiter** [comment]
@blmhemu It seems so, but we are still waiting for the project to become a little bit more consolidate to understand better.

**Comment by onedr0p** [comment]
I'm going to go ahead and close this issue because it seems like this is baked in the new GitopToolkit (Fluxv2). The project is moving along nicely, hope to see you all there sometime :)
