### ISSUE TITLE
Add Helm chart

### ISSUE THREAD

**Issue by mr-smithers-excellent** [topfreegames/fluxcloud#9]
Would love to see a Helm chart for ease of templated deployments. Saw a PR for this in the original repo. Happy to cherry pick from it or create a new one from scratch if need be.

**Comment by marcosnils** [comment]
> Would love to see a Helm chart for ease of templated deployments. Saw a PR for this in the original repo. Happy to cherry pick from it or create a new one from scratch if need be.

Sounds like a good idea. Happy to review if you send a PR here.
